spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot_jpa_starter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
justauth:
  enabled: true
  type:
    github:
      client-id: 2917d3df2590484f0b7f
      client-secret: d47162aee0647f05d822e2507f6ccc5d98e95ded
      redirect-uri: http://igry2v.natappfree.cc/auth/github/callback
    weibo:
      client-id: 227955467
      client-secret: a64d03e26a6a8f769e5ebc7a697f8c18
      redirect-uri: http://c7trbk.natappfree.cc/auth/weibo/callback
logging:
  level:
    xyz.guqing.app: debug
server:
  port: 8081