server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/creek-dev/db/creek;AUTO_SERVER=TRUE
    username: admin
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
creek:
  security:
    oauth2:
      jwt:
        public-key-location: classpath:app.pub
        private-key-location: classpath:app.key
logging:
  level:
    xyz.guqing.creek: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
