server:
  port: 8086
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    # 使用h2数据库
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.creek/db/creek
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    initialization-mode: never
    username: root
    password: 123456
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
justauth:
  enabled: true
  type:
    github:
      client-id:
      client-secret:
      redirect-uri:
    weibo:
      client-id:
      client-secret:
      redirect-uri:
auth0:
  issuer: https://your-domain.eu.auth0.com/
  apiAudience: http://your-audience
logging:
  level:
    xyz.guqing.creek: debug
