spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/springboot-jpa-starter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      initial-size: 10
      min-idle: 15
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
justauth:
  enabled: true
  type:
    github:
      client-id: 2917d3df2590484f0b7f
      client-secret: d47162aee0647f05d822e2507f6ccc5d98e95ded
      redirect-uri: http://yikgj4.natappfree.cc/auth/github/callback
logging:
  level:
    xyz.guqing.app: debug